Remove development-based changes that aren't necessary, update CI to run tests again

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,64 +18,62 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3.9.0
         with:
           distribution: 'zulu'
-          java-version: 11
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
+          java-version: 17
+
+      - name: Setup gradle
+        uses: gradle/gradle-build-action@v2
+
+      - name: AVD cache
+        uses: actions/cache@v3
+        id: avd-cache
         with:
-          distribution: 'zulu'
-          java-version: 11
-          cache: 'gradle'
+          path: |
+            ~/.android/avd/*
+            ~/.android/adb*
+          key: avd-30
 
-# Temporarily disabling UI tests to perform an alpha release. Tests pass locally.
-#      - name: Run Enro UI Tests
-#        uses: reactivecircus/android-emulator-runner@v2
-#        id: testing
-#        continue-on-error: true
-#        with:
-#          api-level: 29
-#          force-avd-creation: false
-#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-#          script: |
-#            adb logcat -c                             # clear logs
-#            touch ~/appemulator.log                    # create log file
-#            chmod 777 ~/appemulator.log                # allow writing to log file
-#            adb logcat >> ~/appemulator.log &          # pipe all logcat messages into log file as a background process
-#            ./gradlew :enro:connectedCheck
-#
-#      - name: Upload Failing Test Report Log
-#        if: steps.testing.outcome != 'success'        # upload the generated log on failure of the tests job
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: logs
-#          path: ~/appemulator.log # path to where the log is
-#
-#      - name: Fail for UI Test
-#        if: steps.testing.outcome != 'success'
-#        run: exit 1
-#
-#      - name: Run Enro UI Tests (Hilt)
-#        uses: reactivecircus/android-emulator-runner@v2
-#        with:
-#          api-level: 29
-#          force-avd-creation: false
-#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-#          script: ./gradlew :enro:hilt-test:connectedCheck
-
-      - name: Run Enro Unit Tests
+      - name: Create AVD and generate snapshot for caching
+        if: steps.avd-cache.outputs.cache-hit != 'true'
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: 29
-          script: ./gradlew :enro:testDebugUnitTest
+          api-level: 30
+          arch: x86_64
+          force-avd-creation: false
+          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: false
+          script: echo "Generated AVD snapshot for caching"
 
-      - name: Run Modularised Example Tests
+      - name: Run Enro Tests
         uses: reactivecircus/android-emulator-runner@v2
+        id: testing
+        continue-on-error: true
         with:
-          api-level: 29
-          script: ./gradlew :modularised-example:app:testDebugUnitTest
+          api-level: 30
+          arch: x86_64
+          force-avd-creation: false
+          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+          disable-animations: true
+          script: |
+            adb logcat -c                             # clear logs
+            touch ~/appemulator.log                    # create log file
+            chmod 777 ~/appemulator.log                # allow writing to log file
+            adb logcat >> ~/appemulator.log &          # pipe all logcat messages into log file as a background process
+            ./gradlew :enro:connectedCheck :enro:testDebugUnitTest :enro:hilt-test:connectedCheck :modularised-example:app:testDebugUnitTest
+
+      - name: Upload Failing Test Report Log
+        if: steps.testing.outcome != 'success'        # upload the generated log on failure of the tests job
+        uses: actions/upload-artifact@v2
+        with:
+          name: logs
+          path: ~/appemulator.log # path to where the log is
+
+      - name: Fail for Test
+        if: steps.testing.outcome != 'success'
+        run: exit 1
 
       - name: Install gpg secret key
         run: cat <(echo -e "${{ secrets.PUBLISH_SIGNING_KEY_LITERAL }}") | gpg --batch --import
